server:
  port: 8092

spring:
  profiles:
    active: dev
  application:
    name: summercloud-task-service
  config:
    import:
      - optional:nacos:summercloud.yaml?group=DEV_GROUP?refresh=true
      - optional:nacos:${spring.application.name}.yaml?group=DEV_GROUP?refresh=true
  cloud:
    nacos:
      server-addr: 192.168.223.100:8848  # nacos地址
      discovery:
        namespace:
        group: DEV_GROUP
      config:
        namespace:
        group: DEV_GROUP
    sentinel:
      eager: true  # 取消控制台懒加载
      transport:
        dashboard: 192.168.223.100:9090  # sentinel dashboard地址
        port: 8719  # sentinel api port
      # sentinel配置持久化
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.223.100:8848
            dataId: ${spring.application.name}
            groupId: DEV_GROUP
            data-type: json
            rule-type: flow

#不需要鉴权的url
not:
  authentication:
    urls: /swagger-ui/**,/swagger-resources/**,/v2/**,/task/health,/task/client/getAllArchiveNodes,/task/client/getAllUsers