server:
  port: 8092

spring:
  profiles:
    active: dev
  application:
    name: task-service

  elasticsearch:
    uris: 192.168.223.100:9200

  data:
    redis:
      host: 192.168.223.100
      port: 6379
      database: 0
      password: root
      timeout: 5000
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-wait: 5000
          min-idle: 5
          max-idle: 10
          time-between-eviction-runs: 1000

  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml

  mail:
    host: smtp.qq.com
    port: 465
    username: 2544894086@qq.com
    password:
    default-encoding: UTF-8
    properties:
      mail:
        debug: false
        smtp:
          ssl:
            enable: true
            required: false
          auth: true
          timeout: 25000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl:
  job:
    admin:
      addresses: http://192.168.223.100:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: task-service-executor
      address:
      ip:
      port: 9999
      logpath: ./logs/task-service/xxl-job/jobhandler
      logretentiondays: 7

management:
  health:
    db:
      enabled: false

jwt:
  secret:
    key: summercloud

mail:
  open:
    true
  from: 2544894086@qq.com
  to: 2544894086@qq.com
  cc: 2544894086@qq.com

#不需要鉴权的url
not:
  authentication:
    urls: /swagger-ui/**,/swagger-resources/**,/v2/**,/task/health,/task/client/getAllArchiveNodes,/task/client/getAllUsers

task:
  threadpool:
    config:
      corePoolSize: 5
      maximumPoolSize: 10
      keepAliveTime: 60
      queueCapacity: 1024
  api-log:
    enabled: true
    log-persist-interval: 1
    log-cleanup-interval: 12
    expire-days: 7

archive:
  service:
    url: ${ARCHIVE_SERVICE_ENDPOINT:http://localhost:8091}

user:
  service:
    url: ${USER_SERVICE_ENDPOINT:http://localhost:8093}