server:
  port: 8092

spring:
  profiles:
    active: dev
  application:
    name: task-service
  redis:
    host: 192.168.223.100
    port: 6379
    database: 0
    password: root
    timeout: 30000
    lettuce:
      pool:
        max-active: 10
        max-wait: 2
        min-idle: 5
        max-idle: 10
  shardingsphere:
    datasource:
      names: ds0
      default-data-source-name: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.223.100:3306/summercloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: Wsw19980801.
        connection-timeout: 60000
        idle-timeout: 500000
        max-lifetime: 540000
        minimum-idle: 5
        maximum-pool-size: 20
        pool-name: HikariPool-task
    sharding:
      tables:
        task_job:
          actualDataNodes: ds0.task_job_$->{[20230401,20230501]}
          tableStrategy:
            standard:
              shardingColumn: created_time
              preciseAlgorithmClassName: com.wsw.summercloud.task.config.CustomShardingAlgorithm
              rangeAlgorithmClassName: com.wsw.summercloud.task.config.CustomShardingAlgorithm
        task_job_record:
          actualDataNodes: ds0.task_job_record_$->{[20230401,20230501]}
          tableStrategy:
            standard:
              shardingColumn: created_time
              preciseAlgorithmClassName: com.wsw.summercloud.task.config.CustomShardingAlgorithm
              rangeAlgorithmClassName: com.wsw.summercloud.task.config.CustomShardingAlgorithm
    props:
      max:
        connections:
          size:
            per:
              query: 20
      sql:
        show: true

  mail:
    host: smtp.qq.com
    port: 465
    username: 2544894086@qq.com
    password:
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          timeout: 25000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl:
  job:
    admin:
      addresses: http://192.168.223.100:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: task-service-executor
      address:
      ip:
      port: 9999
      logpath: ./logs/task-service/xxl-job/jobhandler
      logretentiondays: 7

management:
  health:
    db:
      enabled: false

jwt:
  secret:
    key: summercloud

mail:
  open:
    true
  from: 2544894086@qq.com
  to: 2544894086@qq.com
  cc: 2544894086@qq.com

#不需要鉴权的url
not:
  authentication:
    urls: /swagger-ui/**,/swagger-resources/**,/v2/**,/task/health,/task/hello,/task/createTasks