apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: archive
  template:
    metadata:
      labels:
        app: archive
    spec:
      containers:
        - image: summer15/archive-service:1.0.0
          name: archive-container
          imagePullPolicy: IfNotPresent
          env:
            - name: TASK_SERVICE_ENDPOINT
              value: http://task-service:8092
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 60
            periodSeconds: 10