apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - image: summer15/task-service:1.0.0
          name: task-container
          imagePullPolicy: IfNotPresent