server:
  port: 4000

spring:
  profiles:
    active: dev
  application:
    name: summercloud-gateway
  config:
    import:
      - optional:nacos:summercloud.yaml?group=DEV_GROUP?refresh=true
      - optional:nacos:${spring.application.name}.yaml?group=DEV_GROUP?refresh=true
  cloud:
    nacos:
      server-addr: 192.168.223.100:8848  # nacos地址
      discovery:
        namespace:
        group: DEV_GROUP
      config:
        namespace:
        group: DEV_GROUP
    sentinel:
      eager: true  # 取消控制台懒加载
      transport:
        dashboard: 192.168.223.100:9090  # sentinel dashboard地址
        port: 8719  # sentinel api port
      # sentinel配置持久化
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.223.100:8848
            dataId: ${spring.application.name}
            groupId: DEV_GROUP
            data-type: json
            rule-type: flow
    gateway:
      discovery:
        locator:
          enabled: false  # 是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false
      # 路由规则配置
      routes:
        # user服务
        - id: summercloud-user-service
          uri: lb://summercloud-user-service
          predicates:
            - Path=/summercloud-user-service/**
          filters:
            - StripPrefix=1
        # task服务
        # 路由ID
        - id: summercloud-task-service
          # gateway自动从nacos获取summercloud-task-service可用节点进行转发
          # 默认会将所有gateway uri转发
          uri: lb://summercloud-task-service
          predicates: # 谓词
            - Path=/summercloud-task-service/**  # 4000/summercloud-task-service/task/select/byid -> 8092/summercloud-task-service/task/select/byid
            - After=2020-11-12T00:00:00.000+08:00[Asia/Shanghai]  # 2020-11-12后该微服务才上线，暴露接口
          filters: # 过滤器
            - StripPrefix=1  # 忽略掉第一层前缀进行转发 4000/summercloud-task-service/task/select/byid -> 8092/task/select/byid
        # archive服务
        - id: summercloud-archive-service
          uri: lb://summercloud-archive-service
          predicates:
            - Path=/summercloud-archive-service/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          # gateway网关上所有URI都应用以下跨域设计
          '[/**]':
            # 允许携带认证信息
            allow-credentials: true
            # 允许所有来源进行跨域访问
            allowedOriginPatterns:
              - "*"
            # 允许跨域请求里的head字段
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            # 缓存时长 1小时
            max-age: 3600
