version: '3.8'
services:
  archive-service:
    image: summer15/archive-service:1.0.0
    container_name: archive-service
    restart: always
    ports:
      - '8091:8091'
      - '10011:10011'
    environment:
      TASK_SERVICE_ENDPOINT: "http://192.168.223.100:8092"
      JAVA_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=10011 -Dcom.sun.management.jmxremote.port=10011 -Djava.rmi.server.hostname=192.168.223.100 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./"

  task-service:
    image: summer15/task-service:1.0.0
    container_name: task-service
    restart: always
    ports:
      - '8092:8092'
      - '10012:10012'
    environment:
      JAVA_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=10012 -Dcom.sun.management.jmxremote.port=10012 -Djava.rmi.server.hostname=192.168.223.100 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./"

  user-service:
    image: summer15/user-service:1.0.0
    container_name: user-service
    restart: always
    ports:
      - '8093:8093'
      - '10013:10013'
    environment:
      JAVA_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=10013 -Dcom.sun.management.jmxremote.port=10013 -Djava.rmi.server.hostname=192.168.223.100 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./"

