version: '3.8'
services:
  archive-service:
    image: summer15/archive-service:1.0.0
    container_name: archive-service
    restart: always
    ports:
      - '8091:8091'
    environment:
      TASK_SERVICE_ENDPOINT: http://192.168.223.100:8092

  task-service:
    image: summer15/task-service:1.0.0
    container_name: task-service
    restart: always
    ports:
      - '8092:8092'

  user-service:
    image: summer15/user-service:1.0.0
    container_name: user-service
    restart: always
    ports:
      - '8093:8093'

